apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    app: my-rc-app
    type: fromt-end
spec:
  template:
    metadata:
      name: nginx-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 4